import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Codebolt docs — 5 top-level sidebars.
 * See DOCUMENTATION_PLAN.md for the full structure and writing rules.
 */
const sidebars: SidebarsConfig = {
  gettingStartedSidebar: [{type: 'autogenerated', dirName: '01_getting-started'}],
  conceptsSidebar: [{type: 'autogenerated', dirName: '02_concepts'}],
  usingCodeboltSidebar: [{type: 'autogenerated', dirName: '02_using-codebolt'}],
  guidesSidebar: [{type: 'autogenerated', dirName: '03_guides'}],
  buildSidebar: [{type: 'autogenerated', dirName: '04_build-on-codebolt'}],
  referenceSidebar: [{type: 'autogenerated', dirName: '05_reference'}],
};

export default sidebars;
